language: cpp

matrix:
  include:
    - os: linux
      compiler: clang
    - os: linux
      compiler: gcc
    - os: osx
      osx_image: xcode8.3

before_script:
  - mkdir build
  - cd build
  - cmake ..
  
script: make