branches:
  only:
    - master

clone_folder: c:\jbl

before_build:
  - cmd: cd c:\jbl
  - cmd: mkdir build
  - cmd: cd build
  - cmd: echo "Starting build..."
  - cmd: cmake -G "Visual Studio 14 2015" -T "V140"